apiVersion: v1
kind: Service
metadata:
  name: cdc-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    svc: cdc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc-service
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    svc: cdc-service
spec:
  selector:
    matchLabels:
      svc: cdc-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: cdc-service
    spec:
      containers:
      - name: cdc-service
        image: eventuateio/eventuate-cdc-service:0.4.0.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            value: mysqluser
          - name: SPRING_DATASOURCE_PASSWORD
            value: mysqlpw
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: zookeeper:2181
          - name: EVENTUATELOCAL_CDC_DB_USER_NAME
            value: root
          - name: EVENTUATELOCAL_CDC_DB_PASSWORD
            value: rootpassword
          - name: EVENTUATELOCAL_CDC_READER_NAME
            value: MySqlReader
          - name: EVENTUATELOCAL_CDC_OFFSET_STORE_KEY
            value: MySqlBinlog
          - name: EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID
            value: "1234567890"
          - name: EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC
            value: "false"
          - name: JAVA_OPTS
            value: "-Xmx64m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 20
---