apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config
  namespace: eventuate-tram-examples-customers-and-orders
data:
  connection_string: jdbc:mysql://mysql/eventuate
  sql_password: mysqlpw
  sql_user: mysqluser
  sql_driver: com.mysql.jdbc.Driver